build-clang: checkout to https://github.com/krasCGQ/scripts/commit/306b6e524496e7ee1fe8198d18de21c40f3c2efd
Signed-off-by: Raphiel Rollerscaperers <raphielscape@outlook.com>

diff --git a/build-clang b/build-clang
--- a/build-clang
+++ b/build-clang
@@ -1,9 +1,12 @@
 #!/usr/bin/env bash
-# shellcheck disable=SC1117
-# Clang compilation script
-# Copyright (C) 2018 Nathan Chancellor
-# Copyright (C) 2018 Albert I (krasCGQ)
+#
 # SPDX-License-Identifier: GPL-3.0-or-later
+#
+# Copyright (C) 2018-2019 Nathan Chancellor
+#
+# Copyright (C) 2018-2019 Albert I (krasCGQ)
+#
+# Clang compilation script
 
 
 ###############
@@ -12,30 +15,32 @@
 #             #
 ###############
 
+# Actual folder this script is located
+SCRIPT_FOLDER="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
+
+# Folder that will house the source and build files
+MAIN_FOLDER=${HOME}/clang-build
+
+# Folder that will hold binutils source
+BINUTILS_FOLDER=${MAIN_FOLDER}/binutils
+
+# Folder that will hold the main LLVM source
+LLVM_FOLDER=${MAIN_FOLDER}/llvm-project
+
+# Folder that will hold all of the build files and compiled code
+BUILD_FOLDER=${MAIN_FOLDER}/build
+
 # Colors
 GRN="\033[01;32m"
 RED="\033[01;31m"
 RST="\033[0m"
 
-# Folder that will house the source and build files
-MAIN_FOLDER=${HOME}/KudProject/clang
-
-# Folder that will hold the main LLVM source
-LLVM_FOLDER=${MAIN_FOLDER}/llvm
-
-# Folder that will hold all of the build files and compiled code
-BUILD_FOLDER=${MAIN_FOLDER}/build
-
 # Start tracking time
 START=$(date +"%s")
 
-# Number of threads
-THREADS=$(nproc --all)
-
 # Easy to use version variables
-STABLE_VERSION=7
-MASTER_VERSION=8
-
+STABLE_VERSION=8
+MASTER_VERSION=9
 
 ###############
 #             #
@@ -47,6 +52,7 @@ MASTER_VERSION=8
 function echo() {
     command echo -e "${@}"
 }
+
 
 # Prints a formatted header to point out what is being done to the user
 function header() {
@@ -63,6 +69,7 @@ function header() {
     echo "====$(for i in $(seq ${#1}); do echo "=\c"; done)===="
     echo "${RST}"
 }
+
 
 # Formats the time
 function format_time() {
@@ -99,6 +106,7 @@ function format_time() {
     echo "${TIME_STRING}"
 }
 
+
 # Prints an error in bold red
 function display_error() {
     echo
@@ -106,16 +114,19 @@ function display_error() {
     [[ -z ${2} ]] && echo
 }
 
+
 # Prints an error in bold red and exits the script
 function die() {
     display_error "${@}"
     exit 1
 }
 
+
 # Enforces the value needed for two-part flags
 function enforce_value() {
     [[ ${#} -lt 1 ]] && die "A additional value is needed for one of the flags passed to this script!"
 }
+
 
 # Add a remote if it doesn't exist
 function add_remote() {
@@ -124,38 +135,28 @@ function add_remote() {
     fi
 }
 
+
 function parse_parameters() {
     while [[ ${#} -ge 1 ]]; do
         case ${1} in
             "-b"|"--build-only")
                 BUILD_ONLY=true ;;
 
-            "-d"|"--date")
-                shift && enforce_value "${@}"
-                DATE_OFFSET=${1} ;;
-
             "-I"|"--install-only")
                 INSTALL_ONLY=true ;;
 
-            "-i"|"--install-folder")
+            "-i"|"--install-root")
                 shift && enforce_value "${@}"
-                INSTALL_FOLDER=${1} ;;
-
-            "-S"|"--stock")
-                STOCK=true ;;
+                INSTALL_ROOT=${1} ;;
 
             "-s"|"--stable")
                 VERSION=${STABLE_VERSION} ;;
 
-            "-T"|"--test")
+            "-t"|"--test")
                 TEST=true ;;
 
             "-u"|"--update-only")
                 UPDATE_ONLY=true ;;
-
-            "-v"|"--vendor")
-                shift && enforce_value "${@}"
-                VENDOR=${1} ;;
 
             *) die "Invalid parameter specified!" ;;
         esac
@@ -167,10 +168,8 @@ function parse_parameters() {
     [[ -z ${VERSION} ]] && VERSION=${MASTER_VERSION}
 
     # Folder that will hold the final compiled toolchain
-    [[ -z ${INSTALL_FOLDER} ]] && INSTALL_FOLDER=/opt/kud/${VENDOR:+"${VENDOR,,}-"}clang-${VERSION}.x${TEST:+"-test"}
-
-    # SVN copy of the LLVM folder for revisioning
-    SVN_FOLDER=${MAIN_FOLDER}/svn-${VERSION}.x
+    [[ -z ${INSTALL_ROOT} ]] && INSTALL_ROOT=${TC_FOLDER}
+    INSTALL_FOLDER=${INSTALL_ROOT}/clang-${VERSION}.x${TEST:+"-test"}
 
     # Set compiler
     CC=$(command -v clang || command -v gcc)
@@ -179,141 +178,43 @@ function parse_parameters() {
 }
 
 
-# Rolls back a repo based on a certain date
-function rollback() {
-    if [[ -n ${DATE_OFFSET} ]]; then
-        git checkout "$(git log -1 --format=%H --before="$(date --date="-${DATE_OFFSET} day")")" || die "There was an error rolling back ${FOLDER}!"
-        if [[ -z ${STOCK} && ${FOLDER} = "clang" ]]; then
-            if [[ ${VERSION} -eq ${STABLE_VERSION} ]]; then
-                git cherry-pick 24c9731717 || die "There was an error rolling back ${FOLDER}!"
-                git cherry-pick 513f3b3fb7 || die "There was an error rolling back ${FOLDER}!"
-                git cherry-pick eab6ce7dc6 || die "There was an error rolling back ${FOLDER}!"
-            else
-                git cherry-pick 24c9731717 || die "There was an error rolling back ${FOLDER}!"
-                git cherry-pick 176213e989 || die "There was an error rolling back ${FOLDER}!"
-                git cherry-pick 382ac69d5e || die "There was an error rolling back ${FOLDER}!"
-            fi
-        fi
-    fi
-}
-
-
-# Sync a git project
-function git_sync() {(
-    FOLDER=${1}
-
-    # binutils uses another URL/branch scheme
-    if [[ ${FOLDER} =~ "binutils" ]]; then
-        URL=https://git.linaro.org/toolchain/binutils-gdb
-        # SC2030: Modification of BRANCH is local (to subshell caused by (..) group).
-        # shellcheck disable=SC2030
-        BRANCH=master
-    else
-        # Set URL based on folder
-        case ${FOLDER} in
-            "clang")
-                URL=https://github.com/nathanchance/$(basename "${FOLDER}").git ;;
-            "extra")
-                URL=${LLVM_ORG}clang-tools-extra ;;
-            *)
-                URL=${LLVM_ORG}$(basename "${FOLDER}") ;;
-        esac
-    fi
-
-    # If folder doesn't exist, we need to clone it
-    if [[ ! -d ${FOLDER} ]]; then
-        git clone "${URL}" -b "${BRANCH}" "${FOLDER}" || die "Error cloning ${FOLDER}!"
-    fi
-
-    cd "${FOLDER}" || die "Error moving into ${FOLDER}"
-
-    git clean -fxdq
-
-    # If checking out a branch fails, it's because 'origin/<branch>' and 'upstream/<branch>' exist
-    git checkout ${BRANCH} || git checkout -b ${BRANCH} origin/${BRANCH}
-
-    # For Clang, we need to add an upstream remote and rebase on it
-    if [[ ${FOLDER} = "clang" ]]; then
-        add_remote upstream "${LLVM_ORG}$(basename "${FOLDER}")"
-        git fetch upstream
-        if [[ -n ${STOCK} ]]; then
-            git reset --hard upstream/"${BRANCH}"
-        else
-            git reset --hard origin/"${BRANCH}"
-            git rebase upstream/"${BRANCH}" || die "There was an error rebasing ${FOLDER}!"
-        fi
-    else
-        git fetch origin || die "There was an error fetching updates for ${FOLDER}!"
-        git reset --hard origin/"${BRANCH}" || die "There was an error updating ${FOLDER}!"
-    fi
-
-    # Roll back if necessary
-    rollback
-) || exit 1; }
-
-
-# Syncs a svn project
-function svn_sync() {
-    FOLDER=${1}
-
-    # SC2031: BRANCH was modified in a subshell. That change might be lost.
-    # shellcheck disable=SC2031
-    case ${VERSION} in
-        ${MASTER_VERSION}) URL_SUFFIX=trunk ;;
-        *) URL_SUFFIX=branches/"${BRANCH}" ;;
-    esac
-
-    if [[ ! -d ${FOLDER} ]]; then
-        svn co "https://llvm.org/svn/llvm-project/llvm/${URL_SUFFIX}" "${FOLDER}" || die "There was an error syncing ${FOLDER}!"
-    else
-        cd "${FOLDER}" || die "Error moving into ${FOLDER}"
-        svn update || die "There was an error updating ${FOLDER}!"
-    fi
-
-    LLVM_VERSION_PATCH=$(svn info -r HEAD --show-item revision)
-}
-
-
 # Syncs all necessary projects
 function sync_all() {
-    header "Syncing projects"
-
-    mkdir -p "${MAIN_FOLDER}"
-    cd "${MAIN_FOLDER}" || die "Error creating ${MAIN_FOLDER}!"
+    mkdir -p "${MAIN_FOLDER}" || die "Error creating ${MAIN_FOLDER}!"
 
     # Set branch based on version
     case ${VERSION} in
         ${MASTER_VERSION}) BRANCH=master ;;
-        *) BRANCH="release_${VERSION}0" ;;
+        *) BRANCH="release/${VERSION}.x" ;;
     esac
 
-    # Define the git URL for global use
-    LLVM_ORG=https://git.llvm.org/git/
+    # Update LLVM repo
+    LLVM_URL=https://github.com/llvm/llvm-project
+    if [[ -d ${LLVM_FOLDER} ]]; then
+        header "Updating LLVM"
 
-    git_sync llvm
-    svn_sync "$(basename "${SVN_FOLDER}")"
+        git -C "${LLVM_FOLDER}" reset --hard
+        git -C "${LLVM_FOLDER}" checkout "${BRANCH}" || die "Error changing branches for LLVM!"
+        git -C "${LLVM_FOLDER}" pull --rebase origin "${BRANCH}" || die "Error updating LLVM!"
+    else
+        header "Cloning LLVM"
 
-    mkdir -p "${LLVM_FOLDER}/tools"
-    cd "${LLVM_FOLDER}/tools" || die "Error creating tools folder!"
+        git -C "${SRC_FOLDER}" clone -b "${BRANCH}" ${LLVM_URL} || die "Error cloning LLVM!"
+    fi
+    GIT_REVISION=$(printf "r%s-%s" "$(git -C "${LLVM_FOLDER}" rev-list --count HEAD)" "$(git -C "${LLVM_FOLDER}" rev-parse --short HEAD)")
+    git -C "${LLVM_FOLDER}" apply -v -3 "${SCRIPT_FOLDER}"/patches/llvm-project/0001-Add-CLANG_VERSION_SUFFIX-to-extend-the-version-strin.patch || die "Apply CLANG_VERSION_SUFFIX patch failed!"
+    git -C "${LLVM_FOLDER}" apply -v -3 "${SCRIPT_FOLDER}"/patches/llvm-project/0002-Add-LLD_VERSION_SUFFIX-to-extend-lld-version-string.patch || die "Apply LLD_VERSION_SUFFIX patch failed!"
 
-    git_sync binutils
-    git_sync clang
-    git_sync lld
-    git_sync polly
+    # Update binutils repo
+    if [[ -d ${BINUTILS_FOLDER} ]]; then
+        header "Updating binutils"
 
-    mkdir -p "${LLVM_FOLDER}/projects"
-    cd "${LLVM_FOLDER}/projects" || die "Error creating projects folder!"
+        git -C "${BINUTILS_FOLDER}" pull --rebase origin master || die "Error updating binutils"
+    else
+        header "Cloning binutils"
 
-    git_sync compiler-rt
-    git_sync libcxx
-    git_sync libcxxabi
-    git_sync libunwind
-    git_sync openmp
-
-    mkdir -p "${LLVM_FOLDER}/tools/clang/tools"
-    cd "${LLVM_FOLDER}/tools/clang/tools" || die "Error creating tools folder!"
-
-    git_sync extra
+        git -C "${SRC_FOLDER}" clone --single-branch -b master git://sourceware.org/git/binutils-gdb.git binutils || die "Error cloning binutils"
+    fi
 
     [[ -n ${UPDATE_ONLY} ]] && exit
 }
@@ -331,42 +232,34 @@ function cleanup() {
 function build() {
     header "Building Clang"
 
-    [[ -n ${STOCK} ]] && URL_PREFIX=${LLVM_ORG} || URL_PREFIX=https://github.com/nathanchance/
-
-    cmake -G Ninja \
+    cmake -Wno-dev \
+          -G Ninja \
+          -DCLANG_VERSION_SUFFIX="-${GIT_REVISION}" \
           -DCMAKE_BUILD_TYPE=Release \
-          -DLINK_POLLY_INTO_TOOLS=ON \
           -DCMAKE_C_COMPILER="${CC}" \
-          -DCMAKE_C_FLAGS="-O3 -pthread -fopenmp -march=native" \
+          -DCMAKE_C_FLAGS="-O3 -march=native -mtune=native" \
           -DCMAKE_CXX_COMPILER="${CXX}" \
-          -DCMAKE_CXX_FLAGS="-O3 -pthread -fopenmp -march=native" \
-          -DLLVM_ENABLE_PIC=ON \
+          -DCMAKE_CXX_FLAGS="-O3 -march=native -mtune=native" \
           -DCMAKE_INSTALL_PREFIX="${INSTALL_FOLDER}" \
-          -DLLVM_PARALLEL_COMPILE_JOBS="${THREADS}" \
-          -DLLVM_PARALLEL_LINK_JOBS="${THREADS}" \
-          -DLLVM_LIBDIR_SUFFIX=64 \
-          -DLLVM_ENABLE_THREADS=ON \
+          -DLINK_POLLY_INTO_TOOLS=ON \
+          -DLLD_VERSION_SUFFIX="-${GIT_REVISION}" \
+          -DLLVM_BINUTILS_INCDIR="${BINUTILS_FOLDER}/include" \
+          -DLLVM_CCACHE_BUILD=ON \
+          -DLLVM_ENABLE_BINDINGS=OFF \
+          -DLLVM_ENABLE_OCAMLDOC=OFF \
+          -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;compiler-rt;libcxx;libcxxabi;libunwind;lld;llvm;openmp;polly" \
           -DLLVM_ENABLE_WARNINGS=OFF \
-          -DLLVM_ENABLE_WERROR=OFF \
+          -DLLVM_INCLUDE_DOCS=OFF \
           -DLLVM_INCLUDE_EXAMPLES=OFF \
           -DLLVM_INCLUDE_TESTS=OFF \
-          -DLLVM_INCLUDE_DOCS=OFF \
-          -DLLVM_ENABLE_OCAMLDOC=OFF \
-          -DLLVM_ENABLE_BINDINGS=OFF \
-          -DLLVM_BINUTILS_INCDIR="${LLVM_FOLDER}/tools/binutils/include" \
-          -DLLVM_TARGETS_TO_BUILD="ARM;AArch64" \
-          -DLLVM_OPTIMIZED_TABLEGEN=ON \
-          -DLLVM_USE_LINKER=gold \
-          -DCLANG_VENDOR="${VENDOR:+"${VENDOR} "}" \
-          -DLLVM_VERSION_PATCH="${LLVM_VERSION_PATCH:?}" \
-          -DLLVM_VERSION_SUFFIX="" \
-          -DCLANG_REPOSITORY_STRING="${URL_PREFIX}clang" \
-          "${LLVM_FOLDER}" || die "There was an error running cmake!"
+          -DLLVM_TARGETS_TO_BUILD="X86;ARM;AArch64" \
+          -DLLVM_USE_LINKER="$(for LD in lld gold bfd; do command -v ld.${LD} &>/dev/null && break; done; echo ${LD})" \
+          "${LLVM_FOLDER}"/llvm || die "There was an error running cmake!"
 
     time ninja && SUCCESS=true
     TIME_STRING="$(format_time "${START}" "$(date +"%s")")"
     if [[ -n ${SUCCESS} ]]; then
-        VERSION_STRING=$("${BUILD_FOLDER}"/bin/clang --version | head -1 | perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g' -e 's/[[:space:]]*$//')
+        VERSION_STRING=$("${BUILD_FOLDER}"/bin/clang --version | head -1)
         header "SUCCESS!" "${GRN}"
         echo "${BOLD}Time elapsed:${RST} ${TIME_STRING,,}"
         echo
@@ -384,9 +277,9 @@ function build() {
 
 # Install the toolchain
 function install() {
-    if [[ -z ${TEST} && -d ${INSTALL_FOLDER} ]]; then
-        [[ -d ${INSTALL_FOLDER}-old ]] && rm -rf "${INSTALL_FOLDER}-old"
-        mv "${INSTALL_FOLDER}" "${INSTALL_FOLDER}-old"
+    if [[ -z ${TEST} ]]; then
+        rm -rf "${INSTALL_FOLDER}-old"
+        mv "${INSTALL_FOLDER}" "${INSTALL_FOLDER}-old" 2>/dev/null
     fi
 
     if ! ninja install &>/dev/null; then
@@ -416,3 +309,4 @@ trap 'echo; die "Manually aborted!"' SIGINT SIGTERM
 parse_parameters "${@}"
 sync_build
 install
+exit 0
