[SQUASH]: script: kernel: another cleanup
Signed-off-by: Raphiel Rollerscaperers <raphielscape@outlook.com>

diff --git a/env b/env
--- a/env
+++ b/env
@@ -1,6 +1,5 @@
 #!/usr/bin/env bash
 # shellcheck source=/dev/null
-# shellcheck disable=SC1004
 #
 # Copyright (C) 2018 Raphielscape LLC.
 #
@@ -31,53 +30,16 @@ export TELEGRAM_TOKEN PARSE_BRANCH PARSE_ORIGIN COMMIT_POINT SRCDIR OUTDIR
 
 # Alias echo as teller
 echo() {
-	command echo -e "${@}"
+    command echo -e "${@}"
 }
 
 bold() {
-	command tput bold
-}
-
-colorize() {
-	command tput setaf "${@}"
-}
-
-decolorize() {
-	command tput sgr0
-}
-
-# Colorize errors
-display_error() {
-	echo
-	echo "$(tputaf "${RED}")${1}$(tputz)"
-	[ -z "${2}" ] && echo
-}
-
-# Throw errors in red
-die() {
-	display_error "${@}"
-	exit
-}
-
-# Header colorizer
-header() {
-	if [ -n "${2}" ]; then
-		COLOR=${2}
-	else
-		COLOR=${RED}
-	fi
-	colorize "${COLOR}"
-	echo "====$(for i in $(seq ${#1}); do echo "=\\c"; done)===="
-	echo "==  ${1}  =="
-	# SC2034: i appears unused. Verify it or export it.
-	# shellcheck disable=SC2034
-	echo "====$(for i in $(seq ${#1}); do echo "=\\c"; done)===="
-	decolorize
+    command tput bold
 }
 
 kernelbox() {
-	ANYKERNEL="${HOME}/working/AnyKernel2"
-	ZIP_DIR="${HOME}/working/weeb_zip"
+    ANYKERNEL="${HOME}/working/AnyKernel2"
+    ZIP_DIR="${HOME}/working/weeb_zip"
 }
 
 export ANYKERNEL ZIP_DIR KBUILD_BUILD_USER TOOLCHAIN
@@ -86,63 +48,66 @@ export ANYKERNEL ZIP_DIR KBUILD_BUILD_USER TOOLCHAIN
 rm -rf "${ANYKERNEL_DONE}"
 
 prepare_clang() {
-	header "We're building Clang bois" "${GREEN}"
-
-		# Clang configurations
-		if [ "${WORKER}" = raphielbox ]; then
-			PATH=${HOME}/toolchains/clang-8.x/bin/:$PATH
-			CROSS_COMPILE=aarch64-linux-gnu-
-			CLANG_TRIPLE="aarch64-linux-gnu-"
-		else
-			PATH=${HOME}/LLVM/CLANG/bin:$PATH
-			PATH=${HOME}/GNU/GCC/bin:$PATH
-			CROSS_COMPILE=aarch64-linux-android-
-			CLANG_TRIPLE="aarch64-linux-gnu-"
-		fi
-
-		CLANG_TCHAIN="${SCRIPTDIR}/ccachewrapper clang"
-
-		# Kbuild Sets
-		KBUILD_COMPILER_STRING="$(${CLANG_TCHAIN} --version | head -n 1 |
-			perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g')"
-
-		# Export compiler for announcer
-		COMPILER_USED="$(${CLANG_TCHAIN} --version | head -n 1 |
-			perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g')"
-		CU=clang
-
-	# Scream out the Clang compiler used
-	header "Using toolchain: $(${CLANG_TCHAIN} --version | head -n 1 |
-		perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g')"
-
-	header "Using cross-compiler: $("${CROSS_COMPILE}"gcc --version | head -1)"
+    header "We're building Clang bois" "${GREEN}"
+    
+    # Clang configurations
+    if [ "${WORKER}" = raphielbox ]; then
+        PATH=${HOME}/toolchains/clang-8.x/bin/:$PATH
+		PATH=${HOME}/toolchains/GCC4/bin/:$PATH
+        CROSS_COMPILE="aarch64-linux-gnu-"
+        CLANG_TRIPLE="aarch64-linux-gnu-"
+    else
+        PATH=${HOME}/LLVM/CLANG/bin:$PATH
+        PATH=${HOME}/GNU/GCC/bin:$PATH
+        CROSS_COMPILE="aarch64-linux-android-"
+        CLANG_TRIPLE="aarch64-linux-gnu-"
+    fi
+    
+    CLANG_TCHAIN="${SCRIPTDIR}/ccachewrapper clang"
+    
+    # Kbuild Sets
+    KBUILD_COMPILER_STRING="$(${CLANG_TCHAIN} --version | head -n 1 |
+    perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g')"
+    
+    # Export compiler for announcer
+    COMPILER_USED="$(${CLANG_TCHAIN} --version | head -n 1 |
+    perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g')"
+    CU=clang
+    
+    # Scream out the Clang compiler used
+    header "Using toolchain: $(${CLANG_TCHAIN} --version | head -n 1 |
+    perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g')"
+    
+    header "Using cross-compiler: $("${CROSS_COMPILE}"gcc --version | head -1)"
 }
 
 prepare_gcc() {
-	if [ "${WORKER}" = raphielbox ]; then
-		CROSS_COMPILE="${SCRIPTDIR}/ccachewrapper aarch64-linux-gnu-"
-		COMPILER_USED="$(aarch64-linux-gnu-gcc --version | head -1)"
-		header "Using toolchain: $(aarch64-linux-gnu-gcc --version | head -1)"
-	else
-		PATH=${HOME}/GNU/GCC/bin:$PATH
-		COMPILER_USED="$(aarch64-linux-android-gcc --version | head -1)"
-		CROSS_COMPILE="${SCRIPTDIR}/ccachewrapper aarch64-linux-android-"
-		header "Using toolchain: $(aarch64-linux-android-gcc --version | head -1)"
-	fi
-
-	# Well
-	CU=gcc
+    if [ "${WORKER}" = raphielbox ]; then
+        COMPILER_USED="$(aarch64-linux-gnu-gcc --version | head -1)"
+        CROSS_COMPILE="${SCRIPTDIR}/ccachewrapper aarch64-linux-gnu-"
+        header "Using toolchain: $(aarch64-linux-gnu-gcc --version | head -1)"
+    else
+        PATH=${HOME}/GNU/GCC/bin:$PATH
+        COMPILER_USED="$(aarch64-linux-android-gcc --version | head -1)"
+        CROSS_COMPILE="${SCRIPTDIR}/ccachewrapper aarch64-linux-android-"
+        header "Using toolchain: $(aarch64-linux-android-gcc --version | head -1)"
+    fi
+    
+    # Well
+    CU=gcc
 }
 
-build() {
-	CPU="$(grep -c '^processor' /proc/cpuinfo)"
-	JOBS="$((CPU * 2))"
+# Examine our compilation threads
+# 2x of our available CPUs
+CPU="$(grep -c '^processor' /proc/cpuinfo)"
+JOBS="$((CPU * 2))"
 
-	if [ $CU = clang ]; then
-		make -j${JOBS} O="${OUTDIR}" CC="${CLANG_TCHAIN}" "$@"
-	else
-		make -j${JOBS} O="${OUTDIR}" "$@"
-	fi
+build() {
+    if [ $CU = clang ]; then
+        make -j${JOBS} O="${OUTDIR}" CC="${CLANG_TCHAIN}" "$@"
+    else
+        make -j${JOBS} O="${OUTDIR}" "$@"
+    fi
 }
 
 # Then export the stuff
@@ -158,56 +123,56 @@ export MAINGROUP_ID BUILDSCAPERER_ID STICKER
 
 # Sticc function
 tg_sendstick() {
-	curl -s -X POST "https://api.telegram.org/bot$BOT_API_KEY/sendSticker" \
-		-d sticker="${STICKER}" \
-		-d chat_id=${BUILDSCAPERER_ID} >>/dev/null
+    curl -s -X POST "https://api.telegram.org/bot$BOT_API_KEY/sendSticker" \
+    -d sticker="${STICKER}" \
+    -d chat_id=${BUILDSCAPERER_ID} >>/dev/null
 }
 
 # Push to Channel
 push() {
-	"${TELEGRAM}" -f "${ZIP_DIR}/$ZIPNAME" \
-		-c ${BUILDSCAPERER_ID}
+    "${TELEGRAM}" -f "${ZIP_DIR}/$ZIPNAME" \
+    -c ${BUILDSCAPERER_ID}
 }
 
 # sendcast to group
 tg_sendinfo() {
-	"${TELEGRAM}" -c ${MAINGROUP_ID} -H \
-		"$(
-			for POST in "${@}"; do
-				echo "${POST}"
-			done
-		)"
+    "${TELEGRAM}" -c ${MAINGROUP_ID} -H \
+    "$(
+		for POST in "${@}"; do
+			echo "${POST}"
+		done
+    )"
 }
 
 # sendcast to channel
 tg_channelcast() {
-	"${TELEGRAM}" -c ${BUILDSCAPERER_ID} -H \
-		"$(
-			for POST in "${@}"; do
-				echo "${POST}"
-			done
-		)"
+    "${TELEGRAM}" -c ${BUILDSCAPERER_ID} -H \
+    "$(
+		for POST in "${@}"; do
+			echo "${POST}"
+		done
+    )"
 }
 
 # Debugcasting
 tg_debugcast() {
-	"${TELEGRAM}" -c ${DEBUG_ID} -H \
-		"$(
-			for POST in "${@}"; do
-				echo "${POST}"
-			done
-		)"
+    "${TELEGRAM}" -c ${DEBUG_ID} -H \
+    "$(
+		for POST in "${@}"; do
+			echo "${POST}"
+		done
+    )"
 }
 
 kickstart() {
-	tg_sendinfo "Compilation Started!"
-
-	tg_channelcast "Compiler <code>${COMPILER_USED}</code>" \
-		"Device <b>${DEVICE}</b>" \
-		"Branch <code>${PARSE_BRANCH}</code>" \
-		"Commit Point <code>${COMMIT_POINT}</code>" \
-		"Under <code>$(hostname)</code>" \
-		"Started on <code>$(whoami)</code>"
+    tg_sendinfo "Compilation Started!"
+    
+    tg_channelcast "Compiler <code>${COMPILER_USED}</code>" \
+    "Device <b>${DEVICE}</b>" \
+    "Branch <code>${PARSE_BRANCH}</code>" \
+    "Commit Point <code>${COMMIT_POINT}</code>" \
+    "Under <code>$(hostname)</code>" \
+    "Started on <code>$(whoami)</code>"
 }
 
 # Whenever build is interrupted by purpose, report it
@@ -219,53 +184,53 @@ trap '{
 
 # Interruption Happen, report with sticker
 tg_intstick() {
-	curl -s -X POST "https://api.telegram.org/bot$BOT_API_KEY/sendSticker" \
-		-d sticker="CAADAQADFQADlS0LHvIFwsaTaVjGAg" \
-		-d chat_id=${BUILDSCAPERER_ID} >>/dev/null
+    curl -s -X POST "https://api.telegram.org/bot$BOT_API_KEY/sendSticker" \
+    -d sticker="CAADAQADFQADlS0LHvIFwsaTaVjGAg" \
+    -d chat_id=${BUILDSCAPERER_ID} >>/dev/null
 }
 
 tg_intstickmain() {
-	curl -s -X POST "https://api.telegram.org/bot$BOT_API_KEY/sendSticker" \
-		-d sticker="CAADAQADFQADlS0LHvIFwsaTaVjGAg" \
-		-d chat_id=${MAINGROUP_ID} >>/dev/null
+    curl -s -X POST "https://api.telegram.org/bot$BOT_API_KEY/sendSticker" \
+    -d sticker="CAADAQADFQADlS0LHvIFwsaTaVjGAg" \
+    -d chat_id=${MAINGROUP_ID} >>/dev/null
 }
 
 # Whenever errors occured, report them
 tg_senderror() {
-	tg_sendinfo "Build Throwing Error(s)" \
-		"@raphielscape naaaaa"
-	tg_channelcast "Build Throwing Error(s)"
-	[ -n "${STATUS}" ] &&
-		exit "${STATUS}" ||
-		exit 1
+    tg_sendinfo "Build Throwing Error(s)" \
+    "@raphielscape naaaaa"
+    tg_channelcast "Build Throwing Error(s)"
+    [ -n "${STATUS}" ] &&
+    exit "${STATUS}" ||
+    exit 1
 }
 
 # Announce the completion
 tg_yay() {
-	tg_sendinfo "Compilation for ${DEVICE} Completed yay" \
-		"Haha yes"
+    tg_sendinfo "Compilation for ${DEVICE} Completed yay" \
+    "Haha yes"
 }
 
 # Fin Prober
 fin() {
-	header "Yay! My works took $((DIFF / 60)) minute(s) and $((DIFF % 60)) seconds.~"
-	tg_sendinfo "Build took $((DIFF / 60)) minute(s) and $((DIFF % 60)) seconds"
-	tg_yay
+    header "Yay! My works took $((DIFF / 60)) minute(s) and $((DIFF % 60)) seconds.~"
+    tg_sendinfo "Build took $((DIFF / 60)) minute(s) and $((DIFF % 60)) seconds"
+    tg_yay
 }
 
 # Errored Prober
 finerr() {
-	header "My works took $((DIFF / 60)) minute(s) and $((DIFF % 60)) seconds but it's error..."
-	tg_sendinfo "$(echo -e "Build took $((DIFF / 60)) minute(s) and $((DIFF % 60)) seconds\\nbut it's error...")"
-	tg_senderror
-	exit 1
+    header "My works took $((DIFF / 60)) minute(s) and $((DIFF % 60)) seconds but it's error..."
+    tg_sendinfo "$(echo -e "Build took $((DIFF / 60)) minute(s) and $((DIFF % 60)) seconds\\nbut it's error...")"
+    tg_senderror
+    exit 1
 }
 
 # Some Relatable Aliases
 copy() {
-	command cp -vR "${@}"
+    command cp -vR "${@}"
 }
 
 delett() {
-	command rm -vrf "${@}"
+    command rm -vrf "${@}"
 }
